# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

sudo: false
language: python
python:
  - "2.7"
cache: pip
env:
  global:
    - DB=mysql
    - TREEHERDER_DATABASE_NAME='treeherder'
    - TREEHERDER_DATABASE_USER='root'
    - TREEHERDER_DATABASE_PASSWORD=''
    - TREEHERDER_DATABASE_HOST='localhost'
    - TREEHERDER_MEMCACHED='127.0.0.1:11211'
    - TREEHERDER_MEMCACHED_KEY_PREFIX='treeherder'
    - TREEHERDER_RABBITMQ_USER='guest'
    - TREEHERDER_RABBITMQ_PASSWORD='guest'
    - TREEHERDER_RABBITMQ_VHOST='/'
    - TREEHERDER_RABBITMQ_HOST='127.0.0.1'
    - TREEHERDER_RABBITMQ_PORT='5672'
services:
  - rabbitmq
  - memcached
install:
  - pip install -r requirements/compiled.txt
  - pip install -r requirements/dev.txt
before_script:
  - python setup.py build_ext --inplace
  - mysql -e 'create database treeherder;'
script:
  - py.test tests/$* --runslow --cov-report term-missing --cov treeherder
notifications:
  email: false
